title: OpenShaiya
description: Open source Shaiya development
theme: just-the-docs
color_scheme: dark

url: https://openshaiya.org

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
